# Web Search Agent
search_engine: "lotus" # "bing"
search_top_k: 10
# search_region: "us"
# search_lang: "en"
# page_view_port_size: 1024*40
# serper_api_key: "key here if you use serper"

reading_agent_model: "hosted_vllm/meta-llama/Llama-4-Scout-17B-16E-Instruct"

# azure_bing_search_subscription_key: "key here if you use azure bing"
# azure_bing_search_mkt: "zh-CN" # "en-US"

lotus_corpus: 
- arxiv
- serp

query_save_path: "./scrl/handler/cache/search_result1.json"

server_url_list:
  - "http://localhost:5000"
